spring.application.name=industrial-sensor-platform

# ===============================
# Neon PostgreSQL
# ===============================
spring.datasource.url=${DBURL}
spring.datasource.username=${DBUSERNAME}
spring.datasource.password=${DBPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Server
# ===============================
server.port=${PORT:8080}
server.address=0.0.0.0

# ===============================
# DevTools
# ===============================
spring.devtools.restart.enabled=false